Add discord handler
roots-id/roots-react-native pull request #23
Opened 2022-11-23 23:54 UTC by HunnySajid

related Task : https://github.com/roots-id/roots-react-native/issues/21

ChangeLog:
- Removed sample and used faker to populate credential details
- Improved redux structure to dynamically create (dummy) credentials 

https://user-images.githubusercontent.com/19255438/203665189-17f42e6c-146c-435c-ad50-5f28c5777c8b.mov

2022-11-24 00:12 UTC, 2byrds commented
Great stuff @HunnySajid!
This is close enough to some mocks i did yesterday that I think we can stick with it like you have it, but in case you want a little more context, here those are
See the slides here https://docs.google.com/presentation/d/15gq16k5ZRKe99rOhVuoNrEvksd7vViLkchTKlAkQSwM/edit?usp=sharing
 One thing that I'd like changed, when you accept or deny the credential, the message should show in the chat where you were offered the credential.  We only show messages in your own chat when the interaction wasn't with another person (you self-issued a demo credential).

2022-11-24 00:14 UTC, 2byrds requested changes

2022-11-24 00:14 UTC, 2byrds commented on src/store/thunks/wallet.ts
> +          currentUser._id,
this should post in the chat where you were offered the credential.

2022-11-24 00:14 UTC, 2byrds commented on src/store/thunks/wallet.ts
> +          `Discord social credential denied!`,
This should be posted in the chat where the credential was offered.

2022-11-24 17:28 UTC, HunnySajid commented
@2byrds  Updated the chatId for relevant message after credential acceptance/denial

<img width="323" alt="Screenshot 2022-11-24 at 10 26 41 PM" src="https://user-images.githubusercontent.com/19255438/203840010-15a25152-8c25-4353-88f6-db4822cdd64c.png">


<img width="323" alt="Screenshot 2022-11-24 at 10 25 50 PM" src="https://user-images.githubusercontent.com/19255438/203840022-1345cd6b-3e82-4151-9ee5-6230637e4d5c.png">

2022-11-24 17:31 UTC, HunnySajid commented
@2byrds  regarding the credentials flow diagram you shared, I will look into it more thoroughly over the weekend and will create MR if any changes are needed. 
I also have reviewed some open source projects regarding dids and chat based interfaces. I will check if we can also adopt any practises from there.

2022-11-24 22:10 UTC, 2byrds commented
Looking forward to hearing your ideas. I'm just getting back from our holiday today. I'll be around to meet tomorrow if you can.  We have tons of nonSSI UI/UX work we need to push forward over the next 6 months.

2022-11-24 22:15 UTC, 2byrds commented
> @2byrds  Updated the chatId for relevant message after credential acceptance/denial
> 
> <img width="323" alt="Screenshot 2022-11-24 at 10 26 41 PM" src="https://user-images.githubusercontent.com/19255438/203840010-15a25152-8c25-4353-88f6-db4822cdd64c.png">
> 
> 
> <img width="323" alt="Screenshot 2022-11-24 at 10 25 50 PM" src="https://user-images.githubusercontent.com/19255438/203840022-1345cd6b-3e82-4151-9ee5-6230637e4d5c.png">
> 

Looks great @HunnySajid

2022-11-25 21:03 UTC, 2byrds commented
confirmed on android
![image](https://user-images.githubusercontent.com/681493/204054580-683235c5-50aa-423c-9217-851ca558e01f.png)
confirmed on iphone
![image](https://user-images.githubusercontent.com/681493/204054885-064021cd-6105-4be7-ba44-33c06b950a28.png)
confirmed on web
<img width="1624" alt="image" src="https://user-images.githubusercontent.com/681493/204055086-3aa8f2dc-6831-4b17-b3be-58dfc438a9fb.png">

2022-11-25 21:03 UTC, merged